Androborn/web-hive-team_goit-fs-39

src/sass/utils/_variables.scss

*Styles*
- Change color of variables $accent-color: #487996 to #008cef in _variables.scss

[refactor] change accent color in _variables.scss

---

src/js/drop-menu.js

[fix] Make desktop drop menu foldable 
-  Add function toggleModal, that needs to toggle drop menu (close him at repeated pressing "Послуги")
- Remove function openModal

[fix] Make desktop drop menu foldable

---

src/partials/components/_bg-wrapper.html
src/partials/pages/_order-page.html
src/sass/components/_bg-wrapper.scss

[refactor] Refactor bg-wrapper component classes by BEM
*Classes naming*
- Rename scan__bg-shape--1 to 'bg-wrapper__bg-shape bg-wrapper__bg-shape--1'. and same for the rest classes in _bg-wrapper.html
- Rename scan__bg-shape--1 to ' bg-wrapper__bg-shape--1' and other in _bg-wrapper.scss

Rename bg-wrapper component classes by BEM

---

src/partials/pages/_3d-scanning.html

[refactor] Refactor 3d-scanning page classes by BEM
*Classes naming*
- Rename classes by BEM in _3d-scanning.html

Rename classes by BEM in _3d-scanning.html

---

src/partials/pages/_3d-modeling.html
src/partials/pages/_3d-printing.html
src/partials/pages/_3d-scanning.html
src/partials/pages/_contact.html
src/partials/pages/_order-page.html
src/sass/pages/_3d-modeling.scss
src/sass/pages/_3d-printing.scss
src/sass/pages/_3d-scanning.scss
src/sass/pages/_contact-page.scss
src/sass/pages/_main-page.scss
src/sass/pages/_order-page.scss

[refactor] Global refactoring of commented headings
*HTML markup*
- Add commented headings to _3d-scanning.html
- Add commented headings to _3d-modeling.html
- Add commented headings to _3d-printing.html
- Add commented headings to _contact.html
- Add commented headings to _order-page.html
*Styles*
- Add commented headings to _3d-scanning.scss
- Add commented headings to _order-page.scss
- Add commented headings to _3d-modeling.scss
- Add commented headings to _contact.scss
- Add commented headings to _3d-printing.scss
- Add commented headings to _main-page.scss

Global refactoring of commented headings

---

src/sass/base/_base.scss
src/sass/components/_bg-wrapper.scss
src/sass/components/_contact-info.scss
src/sass/components/_gallery-overlay.scss
src/sass/components/_main-bg-wrapper.scss
src/sass/components/_order-btn.scss
src/sass/components/_order-form.scss
src/sass/layout/_footer.scss
src/sass/layout/_header.scss
src/sass/layout/_mobile-menu.scss
src/sass/pages/_3d-printing.scss
src/sass/pages/_3d-scanning.scss
src/sass/pages/_contact-page.scss
src/sass/pages/_main-page.scss
src/sass/pages/_order-page.scss
src/sass/utils/_variables.scss

[refactor] Refactor color schema variables in _variables.scss
*Styles*
- rename $primary-white-color to $main-background-color
- rename $text-descr to $main-text-color
- rename $textarea-color to $secondary- text-color
- rename $timing-function to $main-timing-function
- rename $btn-shadow-dark to $btn-shadow-hover
- remove $background-btn

Refactor color schema variables in _variables.scss

---

src/3d-modeling.html
src/3d-printing.html
src/3d-scanning.html
src/contact.html
src/index.html
src/order-page.html
src/partials/pages/_order-page.html

*HTML markup*
- Made the correct order for including partials on all HTML-pages
- Delete inline properties on order-page page 
- Include "bg-wrapper" to order-page

[refactor] Include properly components to all HTML pages collector files

---

src/sass/pages/_3d-printing.scss

Checked classes on BEM.
Added font-family to model-examples__title.
Deleted unnecessary markup

Fix _3d-printing.scss

---

src/sass/components/_order-form.scss

Can't change icon color in textarea - need change fill in the sprite.scss.
Can't change select options - need change html file and add new classes

add hover to order-form inputs

---

src/partials/pages/_3d-scanning.html
src/sass/pages/_3d-scanning.scss

[refactor] Refactor 3d-scanning page classes by BEM
*Classes naming*
- Rename classes by BEM in _3d-scanning.html
- Add scan-hero__descrip-box-position and scan-hero__descrip-box-position--left
- Add scan-hero__descrip-box-position and scan-hero__descrip-box-position--right

fix name 3d-scanning page classes by BEM

---

src/partials/layout/_footer.html
src/sass/layout/_footer.scss

Add social icons in footer with hover and focus;
Add svg teg in footer.html;
Add more styles to classes in footer.scss;

Add social icons to footer

---

src/sass/components/_main-bg-wrapper.scss
src/sass/layout/_mobile-menu.scss
src/sass/pages/_3d-modeling.scss
src/sass/pages/_3d-scanning.scss
src/sass/utils/_mixins.scss

not clear line 34 in _mobile-menu.scss.

Add retina mixins to all pages

---

src/partials/pages/_3d-modeling.html
src/sass/pages/_3d-modeling.scss

*Classes naming*
- Renaming elements classes to comply BEM
*Styles*
- Removing inherited font
- Refactoring  3d-modeling.scss

[refactor] Refactoring 3d-modeling page classes by BEM

---

src/partials/components/_main-bg-wrapper.html
src/sass/components/_main-bg-wrapper.scss

Renamed the classes of the "main-bg-wrapper" component according to the BEM methodology

Renamed the classes

---

src/partials/pages/_3d-printing.html
src/sass/pages/_3d-printing.scss

Removes unnecessary classes from the 3d-printing.html;
Refactor styles in the 3d-printing.scss

[refactor] Refactoring the 3d printing page by BEM

---

src/js/phone-list.js

- Made phone numbers list hide by repeated click on it at mobile breakpoint
- Changed openModal function to toggleModal at phone-list.js

[fix] Fix phone list in mobile breakpoint

---

src/3d-modeling.html
src/3d-printing.html
src/3d-scanning.html
src/contact.html
src/index.html
src/js/current-link.js
src/order-page.html
src/partials/layout/_mobile-menu.html
src/sass/layout/_header.scss
src/sass/layout/_mobile-menu.scss
src/sass/utils/_variables.scss

_Styles:_
- Remove all unused styles, that we have;
- Change accent-color to #5c98d2 ;
- Change accent-color-hover to #4382c3;
_HTML markup:_
- Change the link "Послуги" to the paragraph;

[refactor] Refactor mobile menu and change accent + hover colors

---

src/sass/layout/_header.scss

_Styles:_
- Change fill/color of elements to accent-color

[fix] Fix color of elements in header

---

src/sass/components/_contact-info.scss
src/sass/layout/_header.scss
src/sass/pages/_main-page.scss

_Styles:_
- Change color of icon-phone fill to accent-color;
- Change color of anchor-arrow to accent-color;
- Add hover & focus to contact-info links;

[fix] Change color of some elements

---

src/partials/layout/_footer.html
src/sass/layout/_footer.scss

changed class names by BEM
added vendor prefixes
combined repeating classes in styles

[refactor] Refactor footer layout classes by BEM

---

src/partials/pages/_order-page.html
src/sass/pages/_order-page.scss

1. Changed classes according to BEM methodology.
2. Removed unnecessary blocks

[refactor] Global refactoring "take order page" by BEM

---

src/sass/components/_bg-wrapper.scss
src/sass/components/_main-bg-wrapper.scss
src/sass/pages/_3d-scanning.scss
src/sass/pages/_order-page.scss
src/sass/utils/_placeholders.scss

1. Created a template of properties "%bg-sizes", which are applied in the scraper "_bg-wrapper.scss" and "_main-bg-wrapper.scss".
2. Created a template of properties "%scan-process-before" which are applied in the scraper "_3d-scanning.scss".
3. Created a template of properties "%futuristic-flowerpot" which are applied in the "_order-page.scss" scraper

[created] New placeholders created

---

src/partials/pages/_3d-modeling.html
src/partials/pages/_3d-printing.html
src/partials/pages/_3d-scanning.html
src/partials/pages/_main-page.html
src/sass/base/_base.scss
src/sass/layout/_header.scss
src/sass/pages/_main-page.scss

*Styles*
-Remove the hero-container style from the _main-page.scss;
-Remove the overflow:visible style from the header__container class in _header.scss;
-Remove the container class style - overflow:hidden in the _base.scss;
-Add a new class with a modifier  - container--overflow-is-hidden in the _base.scss.
*HTML markup*
-Remove the hero-container class from the _main-page.html;
-Connect the new class with a modifier (container--overflow-is-hidden) to sections with animations (3D SCANNING PROCESS, 3D PRINTING EXAMPLES, 3D MODELS).

[fix] Debug overflow: hidden container bugs

---

src/sass/components/_contact-info.scss
src/sass/components/_order-form.scss
src/sass/pages/_3d-modeling.scss
src/sass/pages/_3d-printing.scss
src/sass/pages/_3d-scanning.scss
src/sass/pages/_contact-page.scss
src/sass/pages/_main-page.scss
src/sass/pages/_order-page.scss
src/sass/utils/_mixins.scss

- created a mixin 'title-styles'
- general properties of titles connected via mixin

[refactor] Refactoring title styles

---

src/partials/layout/_footer.html
src/partials/pages/_3d-modeling.html
src/partials/pages/_3d-printing.html
src/partials/pages/_order-page.html
src/sass/layout/_footer.scss
src/sass/layout/_header.scss
src/sass/pages/_3d-modeling.scss
src/sass/pages/_3d-printing.scss
src/sass/pages/_contact-page.scss
src/sass/pages/_order-page.scss

_HTML-markup:_
- Add class models__item--first to first 2 elements of list for mobile styles at 3d-modeling.html
- Remove class model-examples__item--is-fixed at 3d-printing.html
- Add class  model-examples__item--left 3d-printing.html
- Add modificator --above-btn to avoid using margin top at the btn
- Add div take-order__wrapper for changing margin direction
- Add footer-contact__mail-wrapper  for changing margin direction
_Styles:_
- Change margin direction to bottom right at 3d-modeling.scss
- Add modificator --first to model-item for changing margin direction at mobile version
- remove unnecessary styles from  process-description__button
- dont remove margin-top from process-description__text because of display: inline at the process-description__descr
- remove .perenos because it …

change margin directions to bottom, right
